logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"

wiki:
  category_info_url: "https://en.wikipedia.org/w/api.php?action=query&format=json&list=categorymembers&cmtitle=Category:{category}&cmlimit=max"
  headers:
    User-Agent: "Tinker/0.1 (kartikeyapophali@gmail.com)" # key is intentionally not snake_case

index:
  category: "Dinosaurs"
  max_depth: 100 # max depth of the category tree to be indexed; Wikipedia category tree depth generally doesn't exceed 15-20
  filepath: "/aux/data/wiki/v3000/Dinosaurs"
  log_filepath: "/aux/data/wiki/v3000/logs/index/"
  exclude_keywords: # case-insensitive; page or category will be excluded if any of these keywords/phrases are present in the title
    - "list of" # lists are not properly handled currently, will visit them later
    - "lists of"
    - "bird" # birds are included in the Dinosaurs wikipedia category, but we don't want to index them

rag:
  log_filepath: "/aux/data/wiki/v3000/logs/rag/"
  qa_logs_filepath: "/aux/data/wiki/v3000/logs/qa/"
  hybrid_join_mode: "reciprocal_rank_fusion"
  top_k:
    embedding_retriever: 9
    bm25_retriever: 3
    document_joiner: 12

openai:
  embedding_model: "text-embedding-3-small"
  llm_model: "gpt-4o-mini"
