logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"

wiki:
  category_info_url: "https://en.wikipedia.org/w/api.php?action=query&format=json&list=categorymembers&cmtitle=Category:{category}&cmlimit=max"
  headers:
    User-Agent: "Tinker/0.1 (kartikeyapophali@gmail.com)" # intentionally not snake_case

# Data version: either v100 or v3000 (refers to the approximate number of pages in the dataset)
data_ver: "v100"